web/router.ex
defmodule AuthedApp.Router do
  use AuthedApp.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug AuthedApp.CurrentUser
  end

  pipeline :with_api_session do
    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource
    plug AuthedApp.CurrentUser
  end

  pipeline :login_required do
    plug Guardian.Plug.EnsureAuthenticated, handler: AuthedApp.GuardianErrorHandler
  end

  pipeline :admin_required do
    plug Guardian.Plug.EnsureAuthenticated, handler: AuthedApp.Admin.GuardianErrorHandler
    plug AuthedApp.CheckAdmin
  end

  pipeline :api_login_required do
    plug Guardian.Plug.EnsureAuthenticated, handler: Guardian.Plug.ErrorHandler
  end

  pipeline :api_admin_required do
    plug Guardian.Plug.EnsureAuthenticated, handler: AuthedApp.API.Admin.GuardianErrorHandler
    plug AuthedApp.CheckAdmin
  end

  scope "/", AuthedApp do
    pipe_through [:browser, :with_session]

    # Public routes.
    get "/", PageController, :index
    resources "/users", UserController, only: [:show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/public", PublicController, :index

    scope "/" do
      # Login required.
      pipe_through [:login_required]
      get "/private", PrivateController, :index
    end

    scope "/admin", Admin, as: :admin do
      # Admin account required
      pipe_through [:admin_required, :login_required]
      resources "/users", UserController, only: [:index]
    end
  end

  scope "/api", AuthedApp.API, as: :api do
    pipe_through [:api, :with_api_session]
    scope "/v1", V1, as: :v1 do
      post "/signup", SessionController, :signup
      put "/login", SessionController, :login
      get "/logout", SessionController, :logout
      get "/public", PublicController, :index
      scope "/" do
        pipe_through [:api_login_required]
        get "/private", PrivateController, :index
      end
      scope "/admin", Admin, as: :admin do
        pipe_through [:api_admin_required]
        resources "/users", UserController, only: [:index]
      end
    end
  end
end

web/views/layout_view.ex
defmodule AuthedApp.LayoutView do
  use AuthedApp.Web, :view

  def navigation_header(assigns) do
    render("navigation_header.html", assigns)
  end

  def footer(assigns) do
    render("footer.html", assigns)
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello AuthedApp!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <%= navigation_header(assigns) %>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

      <%= footer(assigns) %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/footer.html.eex
<div class="col-lg-6">
  <h4>Resources</h4>
  <ul>
    <%= if @current_user do %>
      <li>
        <a href="/private">Private</a>
      </li>
    <%= end %>
    <li>
      <a href="/public">Public</a>
    </li>
  </ul>
</div>

<%= if @current_user && @current_user.is_admin do %>
  <div class="col-lg-6">
    <h4>Admin</h4>
    <ul>
      <li>
        <a href="/admin/users">Users</a>
      </li>
    </ul>
  </div>
<%= end %>

web/templates/layout/navigation_header.html.eex
<nav role="navigation">
  <ul class="nav nav-pills pull-right">
    <%= if @current_user do %>
      <li><%= @current_user.name %>&nbsp;</li>
      <li><%= link("Sign out", to: session_path(@conn, :delete, @current_user), method: "delete") %></li>
    <%= else %>
      <li><%= link "Register", to: user_path(@conn, :new) %></li>
      <li><%= link "Sign in", to: session_path(@conn, :new) %></li>
    <%= end %>
  </ul>
</nav>